### Text Vectorization :-> word convert into number

### BOW>>>>>>>>>>>>>>>>>>>> Bag Of Words

In [2]:
import pandas as pd
import numpy as np

In [3]:
text={"text":["People watch Aiyug","Aiyug watch Aiyug","People write comment", "Aiyug write comment"],"output":[1,1,0,0]}

In [4]:
text=pd.DataFrame(text)

In [5]:
text

text  output
0    People watch Aiyug       1
1     Aiyug watch Aiyug       1
2  People write comment       0
3   Aiyug write comment       0

In [6]:
from sklearn.feature_extraction.text import CountVectorizer

In [7]:
cv=CountVectorizer(lowercase=True,stop_words='english',binary=True)

In [ ]:
bow=cv.fit_transform(text['text'])# ek line mein kaam karta hai: yeh text data ko numerical format mein convert karta hai by counting word occurrences using Bag of Words model.

In [10]:
cv.vocabulary_

{'people': 2, 'watch': 3, 'aiyug': 0, 'write': 4, 'comment': 1}

In [11]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())
print(bow[3].toarray())

[[1 0 1 1 0]]
[[1 0 0 1 0]]
[[0 1 1 0 1]]
[[1 1 0 0 1]]


In [12]:
cv.transform(["hello comment my name watch is parimal"]).toarray()

array([[0, 1, 0, 1, 0]])

### N grams

In [13]:
from nltk.util import ngrams
from nltk.tokenize import word_tokenize

text="I love natural language processing"
tokens=word_tokenize(text)
n=3

trigrams=list(ngrams(tokens,n))
print("trigrams:-",trigrams)

trigrams:- [('I', 'love', 'natural'), ('love', 'natural', 'language'), ('natural', 'language', 'processing')]


### TF-IDF

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer #ek aisa tool hai jo text data ko numerical values mein convert karta hai by calculating TF-IDF (Term Frequency–Inverse Document Frequency) — jo batata hai ki ek word kitna important hai kisi document mein poore corpus ke comparison mein.

text=["i love natural language processing", " i love machine leraning", "i love deep learning"]
vectorizer=TfidfVectorizer()
tfidf_matrix=vectorizer.fit_transform(text)
#print(tfidf_matrix.toarrat())
feature_names=vectorizer.get_feature_names_out()
for doc_index,doc in enumerate(tfidf_matrix.toarray()):#Python ka built-in function hai jo kisi iterable (jaise list) ko iterate karte waqt index ke saath uska item bhi deta hai.
    print("document:-",doc_index+1)
    for word_index, score in enumerate(doc):
        if score>0:
            print(f"{feature_names[word_index]}:{score:.4f}")

document:- 1
language:0.5465
love:0.3227
natural:0.5465
processing:0.5465
document:- 2
leraning:0.6525
love:0.3854
machine:0.6525
document:- 3
deep:0.6525
learning:0.6525
love:0.3854


### Part of Speech Tagging

In [ ]:
# install this:-python -m spacy download en_core_web_sm
import spacy

In [17]:
pos=spacy.load('en_core_web_sm')

In [18]:
doc=pos("i love natural language processing")

In [19]:
doc.text

'i love natural language processing'

In [20]:
doc[3].pos_

'NOUN'

In [ ]:
from nltk.stem import PorterStemmer #k stemming algorithm hai jo words ko unke root form (stem) me convert karta hai. Use hota hai: NLP (Natural Language Processing) me jab aapko similar meaning wale words ko same treat karna hota hai.


st=PorterStemmer()
print(st.stem("loving"))

love


In [22]:
print(st.stem("loving"))
st.stem("loving")

love


'love'