In [56]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [57]:
df=pd.read_csv("Old_Bikes_encoded.csv")

In [58]:
df

price  kms_driven  owner  age  power  brand
0      35000.0     17654.0      1  3.0  110.0      0
1     119900.0     11000.0      1  4.0  350.0      1
2     600000.0       110.0      1  8.0  675.0      2
3      65000.0     16329.0      1  4.0  180.0      0
4      80000.0     10000.0      1  3.0  150.0      3
...        ...         ...    ...  ...    ...    ...
7319   25000.0     48587.0      1  8.0  150.0      5
7320   35000.0     60000.0      1  9.0  220.0      6
7321  450000.0      3430.0      1  4.0  750.0     14
7322  139000.0     21300.0      1  4.0  400.0      6
7323   80000.0      7127.0      1  5.0  220.0      6

[7324 rows x 6 columns]

In [59]:
x=df.drop('price',axis=1)##independent variable
y=df['price']## dependent variable

In [60]:
x

kms_driven  owner  age  power  brand
0        17654.0      1  3.0  110.0      0
1        11000.0      1  4.0  350.0      1
2          110.0      1  8.0  675.0      2
3        16329.0      1  4.0  180.0      0
4        10000.0      1  3.0  150.0      3
...          ...    ...  ...    ...    ...
7319     48587.0      1  8.0  150.0      5
7320     60000.0      1  9.0  220.0      6
7321      3430.0      1  4.0  750.0     14
7322     21300.0      1  4.0  400.0      6
7323      7127.0      1  5.0  220.0      6

[7324 rows x 5 columns]

In [61]:
y

0        35000.0
1       119900.0
2       600000.0
3        65000.0
4        80000.0
          ...   
7319     25000.0
7320     35000.0
7321    450000.0
7322    139000.0
7323     80000.0
Name: price, Length: 7324, dtype: float64

In [62]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.2)

In [63]:
x_train

kms_driven  owner   age  power  brand
4506     68857.0      1  15.0  110.0      0
2758      5740.0      1   6.0  500.0      1
640      28329.0      1   6.0  110.0      5
5824     42966.0      1   7.0  150.0      3
6703      8000.0      1   5.0  500.0      1
...          ...    ...   ...    ...    ...
5191     56000.0      1   9.0  200.0      6
5226     22493.0      1   5.0  500.0      1
5390     17477.0      1   5.0  150.0      6
860      14836.0      1   8.0  150.0      3
7270      8000.0      1  10.0  250.0      4

[5859 rows x 5 columns]

In [64]:
y_train

4506     18000.0
2758    140000.0
640      32000.0
5824     40000.0
6703    160000.0
          ...   
5191     48928.0
5226    114000.0
5390     41000.0
860      40000.0
7270     80000.0
Name: price, Length: 5859, dtype: float64

In [65]:
x_train.shape,y_train.shape,x_test.shape,y_test.shape

((5859, 5), (5859,), (1465, 5), (1465,))

In [66]:
from sklearn.linear_model import LinearRegression

In [67]:
lr=LinearRegression()

In [68]:
lr.fit(x_train,y_train)

LinearRegression()

In [69]:
lr.score(x_train,y_train)

0.7053826605671762

In [70]:
lr.score(x_test,y_test)

0.7586900869386206

In [71]:
prd=lr.predict(x_test)

In [72]:
prd

array([125382.54523531, 216422.20333617,  96966.48595241, ...,
        72233.83615101, 208856.67620686,   9305.60087569])

In [73]:
y_test

3795     88400.0
1562    102850.0
4480     67000.0
3718     30000.0
5887     20000.0
          ...   
4417    395000.0
527     140000.0
3309     54500.0
5077    114000.0
565      36000.0
Name: price, Length: 1465, dtype: float64

In [74]:
from sklearn.svm import SVR
svg=SVR()
svg.fit(x_train,y_train)

SVR()

In [75]:
svg.score(x_train,y_train)

-0.061477777101671016

In [76]:
svg.score(x_test,y_test)

-0.0588109710038629

In [77]:
from sklearn.svm import SVC
svc_obj=SVC()
from sklearn.datasets import load_iris
x,y=load_iris(return_X_y=True)
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.2)
svc_obj.fit(x_train,y_train)
svc_obj.score(x_train,y_train)
svc_obj.score(x_test,y_test)

1.0

In [78]:
svc_obj.predict(x_test)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [79]:
svc_obj.predict(y_test)

ValueError: Expected 2D array, got 1D array instead:
array=[1. 0. 2. 1. 1. 0. 1. 2. 1. 1. 2. 0. 0. 0. 0. 1. 2. 1. 1. 2. 0. 2. 0. 2.
 2. 2. 2. 2. 0. 0.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [ ]:
## KNN classifier algorthim
from sklearn.neighbors import KNeighborsClassifier
knn_obj=KNeighborsClassifier()
knn_obj.fit(x_train,y_train)
knn_obj.score(x_test,y_test)


1.0

In [ ]:
knn_obj.score(x_train,y_train)

0.9666666666666667

In [ ]:
## KNN regression
from sklearn.neighbors import KNeighborsRegressor
knn=KNeighborsRegressor()

In [ ]:
knn.fit(x_train,y_train)

KNeighborsRegressor()

In [ ]:
knn.score(x_train,y_train)

0.9635404578542041

In [ ]:
knn.score(x_test,y_test)

0.9885532591414944

In [ ]:
### Decision tree algorithm
from sklearn.tree import DecisionTreeRegressor
dtr=DecisionTreeRegressor()
dtr.fit(x_train,y_train)


DecisionTreeRegressor()

In [81]:
dtr.score(x_train,y_train)

1.0

In [82]:
dtr.score(x_test,y_test)

1.0

In [83]:
dtr.predict(x_test)

array([1., 0., 2., 1., 1., 0., 1., 2., 1., 1., 2., 0., 0., 0., 0., 1., 2.,
       1., 1., 2., 0., 2., 0., 2., 2., 2., 2., 2., 0., 0.])