In [2]:
import numpy as np # Import the numpy library, which provides useful functions for numerical operations

In [4]:
np.__version__

'2.3.1'

## array and list differenncce

In [9]:
lst=[1,2,3,4,5]
print(lst)
print(len(lst))

arr=np.array(lst)
print(arr)
print("type of arr:",type(arr))


[1, 2, 3, 4, 5]
5
[1 2 3 4 5]
type of arr: <class 'numpy.ndarray'>


In [10]:
lst=list(range(0,21))


In [17]:
arr=np.array(lst)
print(arr)
arr

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [14]:
arr=np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [16]:
arr=np.zeros((5,10))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [20]:
arr=np.ones((5,10))
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [25]:
np.linspace(1,10,7) # 7 points between 1 and 10

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

In [27]:
# 1D array covert to 2D array

arr=np.arange(0,30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [28]:
arr.reshape(5,6) # reshape to 5x6 matrix

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [32]:
arr.reshape(2,15)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [37]:
arr=np.random.randint(1,100,9)
arr

array([54, 85, 88, 29, 22, 91, 16, 98, 10])

In [38]:
arr=np.random.randint(1,5,(5,2))
arr

array([[3, 3],
       [3, 2],
       [1, 4],
       [3, 1],
       [3, 3]])

In [39]:
np.random.random(10)

array([0.60267558, 0.67707927, 0.24385718, 0.92127669, 0.61586816,
       0.82045096, 0.08053505, 0.142113  , 0.74995186, 0.40346864])

In [40]:
np.random.random((5,10))

array([[0.09349255, 0.21490981, 0.59686466, 0.76674577, 0.39940023,
        0.24924374, 0.1984506 , 0.98141934, 0.98933429, 0.14114608],
       [0.61354035, 0.93593009, 0.90861113, 0.62706054, 0.76862823,
        0.30448842, 0.26009306, 0.28982402, 0.8468791 , 0.47282879],
       [0.76460503, 0.7639628 , 0.12398545, 0.97944098, 0.81902187,
        0.40832849, 0.9654114 , 0.44286649, 0.63442219, 0.42242168],
       [0.69785479, 0.18129376, 0.57858435, 0.08560502, 0.41662602,
        0.92764623, 0.56636706, 0.56133667, 0.39468545, 0.41323329],
       [0.02713579, 0.74480527, 0.22097526, 0.29360704, 0.20578654,
        0.43535008, 0.50531857, 0.93852316, 0.72939385, 0.4116829 ]])

In [48]:
arr=np.arange(60).reshape(12,5)
print("size of array;-",arr.shape)
print("size;-",arr.size)
print("diaention:-",arr.ndim)
print("type of array:-",arr.dtype)
print("data type of array:-",arr.itemsize)
print("total size of array:-",arr.nbytes)
print("total size of array:-",arr.size*arr.itemsize)



size of array;- (12, 5)
size;- 60
diaention:- 2
type of array:- int64
data type of array:- 8
total size of array:- 480
total size of array:- 480


In [50]:
# 2d covert to 1d
arr=np.arange(60).reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [53]:
arr.flatten() #. flatten() returns a 1-D array containing all the elements of the array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [54]:
arr.ravel() # flatten the array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [55]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [56]:
arr.shape

(12, 5)

In [57]:
arr.reshape(5,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [58]:
arr.T.shape

(5, 12)

In [60]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [62]:
arr[0]=100


In [63]:
arr

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [64]:
arr=np.arange(60).reshape(12,5)

In [65]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [67]:
arr[5]

array([25, 26, 27, 28, 29])

In [69]:
arr[5,4] 

np.int64(29)

In [72]:
arr[0:5,1:2]

array([[ 1],
       [ 6],
       [11],
       [16],
       [21]])

In [73]:
arr[7:8,4]

array([39])

In [79]:
arr[7:8,4]=100

In [78]:
arr

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38, 100],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59]])

In [82]:
arr[11:5]

array([], shape=(0, 5), dtype=int64)

In [83]:
arr[11,4]

np.int64(59)

In [86]:
arr[-1,-1]


np.int64(59)

In [87]:
arr[11][-1]

np.int64(59)

In [88]:
arr[11][4]

np.int64(59)

## 3D aaray

In [89]:
arr=np.arange(225).reshape(5,15,3)
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [90]:
print("size of array;-",arr.shape)
print("size;-",arr.size)
print("diaention:-",arr.ndim)
print("type of array:-",arr.dtype)
print("data type of array:-",arr.itemsize)
print("total size of array:-",arr.nbytes)
print("total size of array:-",arr.size*arr.itemsize)



size of array;- (5, 15, 3)
size;- 225
diaention:- 3
type of array:- int64
data type of array:- 8
total size of array:- 1800
total size of array:- 1800


In [91]:
arr[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [92]:
arr[0][2:]

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [ ]:
arr[:,0] # 

array([[  0,   1,   2],
       [ 45,  46,  47],
       [ 90,  91,  92],
       [135, 136, 137],
       [180, 181, 182]])

In [95]:
arr[:,0,0]

array([  0,  45,  90, 135, 180])

In [96]:
arr[:,0:1,0:1]

array([[[  0]],

       [[ 45]],

       [[ 90]],

       [[135]],

       [[180]]])

In [99]:
arr[2][3][1]=200
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 200, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [102]:
arr=np.array([1,2,3,4,56])
arr.sort()
arr

array([ 1,  2,  3,  4, 56])

In [103]:
arr+2
arr*arr
arr/arr
arr-arr
arr +arr
arr/2

array([ 0.5,  1. ,  1.5,  2. , 28. ])